WTFitness/Controllers/StaffController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Repository.Interfaces;
using Repository.Models;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using WTFitness.Helpers;

namespace WTFitness.Controllers
{
    [Authorize]
    public class StaffController : Controller
    {
        private IStaffRepository userRepository;
        private IUserRepository userRepo;
        private IWebHostEnvironment hostingEnv;
        public StaffController(IStaffRepository _userRepository, IUserRepository _userRepo, IWebHostEnvironment env)
        {
            userRepository = _userRepository;
            userRepo = _userRepo;
            hostingEnv = env;
        }
        public IActionResult Dashboard()
        {
            List<User> user = new List<User>();
            user = userRepo.GetAllUsers();
            return View(user);
        }
        public IActionResult Index()
        {
            List<User> user = new List<User>();
            user = userRepository.GetAllUsers();
            return View(user);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(User user, IFormCollection form)
        {
            //user.RegistrationDate = DateTime.Now;
            user.IsActive = true;
            //
            user.UserTypeId = 2;
            //
            var fileName = "";
            if (form.Files.Count > 0)
            {
                if (form.Files[0].Length > 0)
                {
                    fileName = HelpersFunctions.ReplacedName(user.Name) + "-" + user.BranchId + "-" + DateTime.Parse(user.RegistrationDate.ToString()).ToString("dd-MM-yyyy") + ".jpg";
                    var webRoot = hostingEnv.WebRootPath;
                    var PathWithFolderName = Path.Combine(webRoot, "images", "users");
                    if (!Directory.Exists(PathWithFolderName))
                    {
                        DirectoryInfo di = Directory.CreateDirectory(PathWithFolderName);
                    }
                    string path = Path.Combine(Directory.GetCurrentDirectory(), PathWithFolderName, fileName);

                    using (var memoryStream = new MemoryStream())
                    {
                        form.Files[0].CopyToAsync(memoryStream);
                        using (var img = Image.FromStream(memoryStream))
                        {
                            HelpersFunctions.FixedSize(img, 320, 320).Save(path, ImageFormat.Jpeg);
                        }
                    }
                }
            }
            user.ImagePath = fileName;
            
            string message = userRepo.CreateUser(user);
            if (!string.IsNullOrEmpty(message))
            {
                TempData["Message"] = message;
                return RedirectToAction();
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Edit(int userId)
        {
            User user = new User();
            user = userRepository.GetUserByUserId(userId);

            return View(user);
        }
        [HttpPost]
        public IActionResult Edit(User user, IFormCollection form)
        {
            var fileName = "";
            if (form.Files.Count > 0)
            {
                if (form.Files[0].Length > 0)
                {
                    fileName = HelpersFunctions.ReplacedName(user.Name) + "-" + user.BranchId + "-" + DateTime.Parse(user.RegistrationDate.ToString()).ToString("dd-MM-yyyy") + ".jpg";
                    var webRoot = hostingEnv.WebRootPath;
                    var PathWithFolderName = Path.Combine(webRoot, "images", "users");
                    if (!Directory.Exists(PathWithFolderName))
                    {
                        DirectoryInfo di = Directory.CreateDirectory(PathWithFolderName);
                    }
                    string path = Path.Combine(Directory.GetCurrentDirectory(), PathWithFolderName, fileName);

                    using (var memoryStream = new MemoryStream())
                    {
                        form.Files[0].CopyToAsync(memoryStream);
                        using (var img = Image.FromStream(memoryStream))
                        {
                            HelpersFunctions.FixedSize(img, 320, 320).Save(path, ImageFormat.Jpeg);
                        }
                    }
                }
            }
            user.ImagePath = fileName;
            string message = userRepo.EditUser(user);
            if (!string.IsNullOrEmpty(message))
            {
                TempData["Message"] = message;
                return RedirectToAction();
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Delete(int userId)
        {
            User user = new User();
            user = userRepository.GetUserByUserId(userId);
            return View(user);
        }
        [HttpPost]
        public IActionResult Delete(User user)
        {
            userRepository.DeleteUser(user.UserId);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Details(int userId)
        {
            User user = new User();
            user = userRepository.GetUserByUserId(userId);
            return View(user);
        }
        [HttpGet]
        public IActionResult ActiveUsers()
        {
            List<User> user = new List<User>();
            user = userRepository.GetActiveUsers();
            return View("~/Views/Staff/Index.cshtml", user);
        }
        [HttpPost]
        [Route("Staff/ActivateUser")]
        public IActionResult ActivateUser(int userId, bool IsActive)
        {
            User user = new User();
            userRepository.ActivateUser(userId, IsActive);
            return Json(user);
        }
    }
}

WTFitness/Views/Shared/_Admin.cshtml
<!doctype html>
<html lang="en" dir="ltr">
@{ string UserName = "";
    var ClaimName = User.Claims.Where(x => x.Type == "UserName").FirstOrDefault();
    if (ClaimName != null)
    {
        UserName = ClaimName.Value;
    }
    string UserRole = "";
    var ClaimRole = User.Claims.Where(x => x.Type == "UserRole").FirstOrDefault();
    if (ClaimRole != null)
    {
        UserRole = ClaimRole.Value;
    }
    int BranchId = 0;
    var ClaimBranch = User.Claims.Where(x => x.Type == "BranchId").FirstOrDefault();
    if (ClaimRole != null)
    {
        BranchId = int.Parse(ClaimBranch.Value);
    }
}
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="icon" href="favicon.ico" type="image/x-icon" />

    <title>WTFitess Center</title>

    <link rel="stylesheet" href="~/css/bootstrap.min.css" />

    <link rel="stylesheet" href="/assets/css/main.css" asp-append-version="true" />
    <link rel="stylesheet" href="/assets/css/theme1.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous" defer />
    <script src="~/js/jquery.min.js"></script>
</head>

<body class="font-montserrat">
    <!-- Page Loader -->
    @*<div class="page-loader-wrapper">
            <div class="loader">
            </div>
        </div>*@

    <div id="main_content">
        <div id="left-sidebar" class="sidebar">
            <img src="~/images/logo.png" />
            <nav id="left-sidebar-nav" class="sidebar-nav">
                @if (UserRole.Equals("Admin"))
                {
                    <ul class="metismenu">
                        <li class="g_heading">Customers</li>
                        <li><a asp-action="Index" asp-controller="Users"><span>All Customers</span></a></li>
                        <li><a asp-action="ActiveUsers" asp-controller="Users"><span>Active Customers</span></a></li>
                        <li><a asp-action="Create" asp-controller="Users"><span>Create Customers</span></a></li>
                        <li class="g_heading">Staff</li>
                        <li><a asp-action="Index" asp-controller="Staff"><span>All Staff</span></a></li>
                        <li><a asp-action="ActiveUsers" asp-controller="Staff"><span>Active Staff</span></a></li>
                        <li><a asp-action="Create" asp-controller="Staff"><span>Create Staff</span></a></li>
                        <li class="g_heading">Search</li>
                        <li><a asp-action="Search" asp-controller="Users" asp-route-SearchType="1"><span>Search By UserId</span></a></li>
                        <li><a asp-action="Search" asp-controller="Users" asp-route-SearchType="2"><span>Search By Name</span></a></li>
                        <li class="g_heading">Kashmir Road</li>
                        <li><a asp-action="MonthlyPaidUsers" asp-controller="Users" asp-route-MonthId="@DateTime.Now.Month" asp-route-YearId="@DateTime.Now.Year" asp-route-BranchId="1"><span>Current Month Paid</span></a></li>
                        <li><a asp-action="MonthlyUnPaidUsers" asp-controller="Users" asp-route-MonthId="@DateTime.Now.Month" asp-route-YearId="@DateTime.Now.Year" asp-route-BranchId="1"><span>Current Month Unpaid</span></a></li>
                        <li><a asp-action="AllTimeFeeManagement" asp-controller="Users" asp-route-BranchId="1"><span>All Time</span></a></li>
                        <li class="g_heading">GT Road</li>
                        <li><a asp-action="MonthlyPaidUsers" asp-controller="Users" asp-route-MonthId="@DateTime.Now.Month" asp-route-YearId="@DateTime.Now.Year" asp-route-BranchId="2"><span>Current Month Paid</span></a></li>
                        <li><a asp-action="MonthlyUnPaidUsers" asp-controller="Users" asp-route-MonthId="@DateTime.Now.Month" asp-route-YearId="@DateTime.Now.Year" asp-route-BranchId="2"><span>Current Month Unpaid</span></a></li>
                        <li><a asp-action="AllTimeFeeManagement" asp-controller="Users" asp-route-BranchId="2"><span>All Time</span></a></li>
                    </ul>
                }
                else if (UserRole.Equals("Branch Manager"))
                {
                    <ul class="metismenu">
                        <li class="g_heading">Customers</li>
                        <li><a asp-action="GetUsersByBranch" asp-controller="Users" asp-route-BranchId="@BranchId"><span>All Customers</span></a></li>
                        <li><a asp-action="ActiveUsersByBranch" asp-controller="Users" asp-route-BranchId="@BranchId"><span>Active Customers</span></a></li>
                        <li><a asp-action="Create" asp-controller="Users"><span>Create Customers</span></a></li>
                        <li class="g_heading">Search</li>
                        <li><a asp-action="Search" asp-controller="Users" asp-route-SearchType="1"><span>Search By UserId</span></a></li>
                        <li><a asp-action="Search" asp-controller="Users" asp-route-SearchType="2"><span>Search By Name</span></a></li>
                        <li class="g_heading">Fee Management</li>
                        <li><a asp-action="MonthlyPaidUsers" asp-controller="Users" asp-route-MonthId="@DateTime.Now.Month" asp-route-YearId="@DateTime.Now.Year" asp-route-BranchId="@BranchId"><span>Current Month Paid</span></a></li>
                        <li><a asp-action="MonthlyUnPaidUsers" asp-controller="Users" asp-route-MonthId="@DateTime.Now.Month" asp-route-YearId="@DateTime.Now.Year" asp-route-BranchId="@BranchId"><span>Current Month Unpaid</span></a></li>
                        <li><a asp-action="AllTimeFeeManagement" asp-controller="Users" asp-route-BranchId="@BranchId"><span>All Time</span></a></li>
                    </ul>
                }
            </nav>
        </div>

        <div class="page">
            <div class="section-body">
                <div class="container-fluid">
                    <div class="row clearfix">
                        <div class="col-lg-6 pt-25">
                            <div class="mb-4">
                                <h4>Welcome @UserName!</h4>
                            </div>
                        </div>
                        <div class="col-lg-6 pt-25 pr-20 rtl">
                            <div class="mb-4" style="text-align: right">
                                <h6><a asp-action="Logout" asp-controller="Account">Logout</a></h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="section-body">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>

WTFitness/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WTFitness</title>

    <environment include="development">
        <link rel="stylesheet" href="~/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/style.css" />
        <link rel="stylesheet" type="text/css" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous" defer />
        <script src="~/js/jquery.min.js"></script>
    </environment>
    <environment exclude="development">
        <link rel="stylesheet" href="~/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/style.css" />
        <link rel="stylesheet" type="text/css" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous" defer />
        <script src="~/js/jquery.min.js"></script>
    </environment>
</head>
<body>
    <header>
        <div class="header-bar">
            <div class="header-bar-inner">
                <nav class="navbar navbar-expand-lg">
                    <a class="navbar-brand" href="/"><img src="/images/logo.png"></a>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="/">All Customers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-action="ActiveUsers" asp-controller="Users">Active Customers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/">Staff</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Create" asp-controller="Users">Create User</a>
                            </li>
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-action="Logout" asp-controller="Account">Logout</a>
                                </li>
                            }
                        </ul>
                    </div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"><img src="/images/menu-button.png"></span>
                    </button>
                </nav>
            </div>
        </div>
    </header>
    <div class="main-body">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer>
        <div class="container">
            &copy; 2021 - WTFitness
        </div>
    </footer>
    @RenderSection("Scripts", required: false)
</body>
</html>